wget autosetup1.googlecode.com/files/authdaemonrc
wget autosetup1.googlecode.com/files/authmysqlrc
wget autosetup1.googlecode.com/files/cacti-nginx.tar.gz
wget autosetup1.googlecode.com/files/CentOS-Base.repo
wget autosetup1.googlecode.com/files/changeyum.sh
wget autosetup1.googlecode.com/files/courier-authlib-0.62.2-1.x86_64.rpm
wget autosetup1.googlecode.com/files/courier-authlib-devel-0.62.2-1.x86_64.rpm
wget autosetup1.googlecode.com/files/courier-authlib-mysql-0.62.2-1.x86_64.rpm
wget autosetup1.googlecode.com/files/Discuz610_UC100_GBK.zip
wget autosetup1.googlecode.com/files/dns.sh
wget autosetup1.googlecode.com/files/dztopw.zip
wget autosetup1.googlecode.com/files/eaccelerator-0.9.5.3.tar.bz2
wget autosetup1.googlecode.com/files/EMOS-Base.repo
wget autosetup1.googlecode.com/files/endpoints.sh
wget autosetup1.googlecode.com/files/fcgi.conf
wget autosetup1.googlecode.com/files/freetype-2.3.8.tar.gz
wget autosetup1.googlecode.com/files/gd-2.0.35.tar.gz
wget autosetup1.googlecode.com/files/glibc-exp.sh
wget autosetup1.googlecode.com/files/hadoop-0.20.2.tar.gz
wget autosetup1.googlecode.com/files/hadoop-0.20.2-append-for-hbase.zip
wget autosetup1.googlecode.com/files/heartbeat-2.1.3.tar.gz
wget autosetup1.googlecode.com/files/httpd-2.2.11.tar.gz
wget autosetup1.googlecode.com/files/httpd-2.2.21.tar.gz
wget autosetup1.googlecode.com/files/httpd-2.2.22.tar.gz
wget autosetup1.googlecode.com/files/httpd-2.2.9.tar.gz
wget autosetup1.googlecode.com/files/httpd-2.4.2.tar.gz
wget autosetup1.googlecode.com/files/iopp.c
wget autosetup1.googlecode.com/files/java.sh
wget autosetup1.googlecode.com/files/jdk.bin
wget autosetup1.googlecode.com/files/jdk-6u20-linux-i586.bin
wget autosetup1.googlecode.com/files/jdk-6u20-linux-i586-rpm.bin
wget autosetup1.googlecode.com/files/jdk-6u20-linux-x64.bin
wget autosetup1.googlecode.com/files/jdk-6u20-linux-x64-rpm.bin
wget autosetup1.googlecode.com/files/jdk-6u20-windows-i586.exe
wget autosetup1.googlecode.com/files/jpegsrc.v6b.tar.gz
wget autosetup1.googlecode.com/files/keystone_data.sh
wget autosetup1.googlecode.com/files/libiconv-1.12.tar.gz
wget autosetup1.googlecode.com/files/libiconv-1.13.tar.gz
wget autosetup1.googlecode.com/files/libiconv-1.9.2.tar.gz
wget autosetup1.googlecode.com/files/libmcrypt-2.5.8.tar.gz
wget autosetup1.googlecode.com/files/libnet.tar.gz
wget autosetup1.googlecode.com/files/libpng-1.2.35.tar.gz
wget autosetup1.googlecode.com/files/libxml2-2.7.3.tar.gz
wget autosetup1.googlecode.com/files/lighttpd-1.4.20.tar.gz
wget autosetup1.googlecode.com/files/mcrypt-2.6.7.tar.gz
wget autosetup1.googlecode.com/files/mcrypt-2.6.8.tar.gz
wget autosetup1.googlecode.com/files/memcache-2.2.3.tgz
wget autosetup1.googlecode.com/files/memcache-2.2.5.tgz
wget autosetup1.googlecode.com/files/mhash-0.9.9.9.tar.gz
wget autosetup1.googlecode.com/files/mhash-0.9.9.tar.gz
wget autosetup1.googlecode.com/files/mm.php
wget autosetup1.googlecode.com/files/Myentunnel-Chinese.rar
wget autosetup1.googlecode.com/files/myget-0.1.2.tar.gz
wget autosetup1.googlecode.com/files/mysql-5.0.22.tar.gz
wget autosetup1.googlecode.com/files/mysql-5.1.31.tar.gz
wget autosetup1.googlecode.com/files/mysql-5.5.19.tar.gz
wget autosetup1.googlecode.com/files/mysql-5.5.2-m2.tar.gz
wget autosetup1.googlecode.com/files/mysql-connector-java-5.1.13-bin.jar
wget autosetup1.googlecode.com/files/nginx.conf
wget autosetup1.googlecode.com/files/nginx-0.7.19.tar.gz
wget autosetup1.googlecode.com/files/nginx-1.2.conf
wget autosetup1.googlecode.com/files/nginx1.conf
wget autosetup1.googlecode.com/files/nginx-cache.conf
wget autosetup1.googlecode.com/files/nginx-init.sh
wget autosetup1.googlecode.com/files/openvpn-2.0.9.tar.gz
wget autosetup1.googlecode.com/files/openvpn-2.0.9-gui-1.0.3-install.exe
wget autosetup1.googlecode.com/files/openvpn-2.2.2.tar.gz
wget autosetup1.googlecode.com/files/opie-24-630src.rpm
wget autosetup1.googlecode.com/files/pcre-7.7.tar.gz
wget autosetup1.googlecode.com/files/pcre-7.9.tar.gz
wget autosetup1.googlecode.com/files/pcre-8.01.tar.gz
wget autosetup1.googlecode.com/files/pcre-8.20.tar.gz
wget autosetup1.googlecode.com/files/php-5.2.10.tar.gz
wget autosetup1.googlecode.com/files/php-5.2.10-fpm-0.5.11.diff.gz
wget autosetup1.googlecode.com/files/php-5.2.13.tar.gz
wget autosetup1.googlecode.com/files/php-5.2.13-fpm-0.5.13.diff.gz
wget autosetup1.googlecode.com/files/php-5.2.17.tar.gz
wget autosetup1.googlecode.com/files/php-5.2.17-fpm-0.5.14.diff.gz
wget autosetup1.googlecode.com/files/php-5.2.17-max-input-vars.patch
wget autosetup1.googlecode.com/files/php-5.2.6.tar.gz
wget autosetup1.googlecode.com/files/php-5.2.6-fpm-0.5.9.diff.gz
wget autosetup1.googlecode.com/files/php-5.2.9.tar.gz
wget autosetup1.googlecode.com/files/php-5.3.10.tar.gz
wget autosetup1.googlecode.com/files/php-5.3.8.tar.gz
wget autosetup1.googlecode.com/files/php-fpm.conf
wget autosetup1.googlecode.com/files/PHPWind_UTF8_6.3.2.zip
wget autosetup1.googlecode.com/files/popvpn%20%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95.rar
wget autosetup1.googlecode.com/files/POPvpn_Build20081223_Setup.rar
wget autosetup1.googlecode.com/files/popvpn_build20090808.rar
wget autosetup1.googlecode.com/files/POPvpn_html.rar
wget autosetup1.googlecode.com/files/POPvpnSetupV1.5.rar
wget autosetup1.googlecode.com/files/ppclient.sh
wget autosetup1.googlecode.com/files/pppd-sql-0.8.0.tar.gz
wget autosetup1.googlecode.com/files/ppserver.sh
wget autosetup1.googlecode.com/files/proxy.conf
wget autosetup1.googlecode.com/files/proxy-cache.conf
wget autosetup1.googlecode.com/files/run.sh
wget autosetup1.googlecode.com/files/SimpleHTTPServerWithUpload.py
wget autosetup1.googlecode.com/files/snmpd.conf
wget autosetup1.googlecode.com/files/snmpd.options
wget autosetup1.googlecode.com/files/stop.sh
wget autosetup1.googlecode.com/files/test%20mail.txt
wget autosetup1.googlecode.com/files/virtio-win-1.1.16.vfd
wget autosetup1.googlecode.com/files/webbench-1.5.tar.gz
wget autosetup1.googlecode.com/files/winkey.exe
wget autosetup1.googlecode.com/files/www-1.2.conf
wget autosetup1.googlecode.com/files/XConvert_for_phpwind.zip
wget autosetup1.googlecode.com/files/XConvert1.3.1.zip
wget autosetup1.googlecode.com/files/ZendOptimizer-3.3.9-linux-glibc23-i386.tar.gz
wget autosetup1.googlecode.com/files/ZendOptimizer-3.3.9-linux-glibc23-x86_64.tar.gz
